### ISSUE TITLE
Sierra?

### ISSUE THREAD

**Issue by jcostanz** [UNC-Libraries/III-ILS-Helpers#1]
Hi, unfortunately I couldn't get this to work for me. but I'm in Sierra. do you know if that would matter?

**Comment by kspurgin** [comment]
Hi, 

If Sierra outputs the data from Create Lists in a different format, then this wouldn't work. I don't have Sierra, so I don't know what its output looks like. 

If you send me a sample/copy of the output file you are trying to run the script on, I can say more about what the problem is. myGitHubUserName AT email DOT unc DOT edu

**Comment by kspurgin** [comment]
Just to follow up... I have had a number of reports that this DOES work on outputs from Sierra's Create Lists, so that isn't the issue in itself.
